# Start with Ubuntu 22.04
FROM ubuntu:22.04

# Set the environment variable to prevent interactive installation prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update and install networking tools
RUN apt-get update && apt-get install -y \
    dnsutils \
    iputils-ping \
    curl \
    net-tools \
    tcpdump \
    iproute2 \
    wget \
    traceroute \
    nmap \
    iperf3 \
    inetutils-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the entrypoint to bash
ENTRYPOINT ["/bin/bash"]