apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-network-tools-pod
spec:
  containers:
  - name: ubuntu-network-tools-container
    image: ghopin/ubuntu-dns-pod:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]